
server:
  port: ${PORT:8081}
spring:
  application:
    name:  gateway
  cloud:
     gateway:
      routes:
      - id: UsersService
        uri: http://localhost:8082/
        predicates:
         Path=/api/users/**
      - id: Air_Travel
        uri: http://localhost:8085/
        predicates:
         Path=/api/airTravels/**   
      - id: Sea_Travel
        uri: http://localhost:8084/
        predicates:
         Path=/api/SeaTravels/**   
      - id: Auth_Service
        uri: http://localhost:8083/
        predicates:
         Path=/auth/**    
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

   